import json,pathlib,hashlib,datetime
D=pathlib.Path('/tmp/cvg-audit-deliveries-ufq9_ejh/frontend')
f=[]
def add(id,severity,cards,title,evidence,source,recommendation,kind='STATIC',confidence='HIGH'):
 f.append(dict(id=id,severity=severity,cards=cards,title=title,evidence=evidence,source=source,recommendation=recommendation,status='OPEN',evidence_kind=kind,confidence=confidence))
add('FE01','High',['PROD-29'],'Drawer fechado amplia Inbox 1024 para 1318 pixels e continua no DOM acessível','inbox-1024-selected.png; browser-observations.json: geometry 1318/1024','apps/desk-web/src/pages/Inbox.css:17; apps/desk-web/src/pages/Inbox.tsx:1240','Fechar drawer com geometria contida e inert/aria-hidden conforme estado; medir scrollWidth e navegação por Tab nos breakpoints.','BROWSER+STATIC')
add('FE02','High',['PROD-19'],'Operação no contexto incompleta: transferência desabilitada; cadastro abre lista genérica','inbox-1440-selected.png','apps/desk-web/src/pages/Inbox.tsx:1127; apps/desk-web/src/pages/Inbox.tsx:1249','Implementar atribuição/status/handoff/transferência/tags e links exatos; contexto de tarefa/nota/tutor/paciente via recursos autorizados.','BROWSER+STATIC')
add('FE03','High',['PROD-19'],'Busca e contagens consideram apenas conversas carregadas; parâmetros de consulta não incluem busca/status/responsável/labels','render.cjs fixture anuncia segunda página; browser-observations.json registra consultas','apps/desk-web/src/pages/Inbox.tsx:335; apps/desk-web/src/pages/Inbox.tsx:880; apps/desk-web/src/pages/Inbox.tsx:894','Levar busca/filtros ao servidor autorizado e distinguir totais globais dos itens carregados.')
add('FE04','Medium',['PROD-20'],'Timeline rotula qualquer histórico como Hoje','inbox-375-selected.png e inbox-1440-selected.png; fixture usa 10/11 setembro','apps/desk-web/src/pages/Inbox.tsx:1162','Agrupar por data local real e tratar timezone, mudança de dia e empates.','BROWSER+STATIC')
add('FE05','High',['PROD-20'],'asset:// é chip sem ação; documento/vídeo não têm componente de leitura completo','inbox-1440-selected.png, arquivo exame-luna-fixture.pdf sem botão/link','apps/desk-web/src/pages/Inbox.tsx:1164','Resolver leitura/download autorizado e estados pending/infected/revogado/expirado; não reconduzir mídia para URL arbitrária.','BROWSER+STATIC')
add('FE06','Medium',['PROD-20'],'Rascunhos e intenções existem só em memória do Inbox; sair/remontar perde estado','Inspeção state/ref, nenhuma persistência por conversa na página','apps/desk-web/src/pages/Inbox.tsx:246; apps/desk-web/src/pages/Inbox.tsx:274','Definir recuperação segura por identidade/conversa durante 401/relogin/navegação; preservar intenção idempotente sem compartilhar dados entre usuários.')
add('FE07','High',['PROD-21'],'Tarefa não permite atribuição/vínculos no formulário nem abrir conversa do card','tasks-create-1440.png: apenas título/descrição/prioridade/prazo; assignee 10000000','apps/desk-web/src/pages/Tasks.tsx:129; apps/desk-web/src/pages/Tasks.tsx:357','Seletores humanos autorizados e edição/links de conversa/tutor/paciente/assignee; provar persistência e atualização.','BROWSER+STATIC')
add('FE08','High',['PROD-22'],'Nota exige ID técnico e apresenta referência truncada sem navegação','notes-create-1440.png: ID da referência e #20000000','apps/desk-web/src/pages/Notes.tsx:95; apps/desk-web/src/pages/Notes.tsx:170; apps/desk-web/src/pages/Notes.tsx:243','Pesquisa/seletor por nomes, preseleção contextual e links exatos.','BROWSER+STATIC')
add('FE09','High',['PROD-22','PROD-25'],'Ficha de contato carrega/cria notas apenas na primeira conversa','Inspeção do caminho loadContactNotes e criação','apps/desk-web/src/pages/Contacts.tsx:188; apps/desk-web/src/pages/Contacts.tsx:305','Agregar notas de todas conversas autorizadas com procedência e paginação; evitar escolha implícita da primeira conversa.')
add('FE10','Medium',['PROD-23'],'Alertas têm ack/resolve mas não navegam ao recurso relacionado','alerts-1440.png: fixture tem conversationId/taskId, sem link','apps/desk-web/src/pages/Alerts.tsx:105; apps/desk-web/src/pages/Alerts.tsx:245','Adicionar links autorizados para tarefa/conversa e reconciliar status entre operadores.','BROWSER+STATIC')
add('FE11','High',['PROD-24'],'Grupos só exibem membros; instrução para adicionar pela ficha não corresponde a controle ali','ContactGroups mostra membros e texto de orientação; Contacts apenas renderiza badges grupos/labels','apps/desk-web/src/pages/ContactGroups.tsx:354; apps/desk-web/src/pages/ContactGroups.tsx:363; apps/desk-web/src/pages/Contacts.tsx:452','Conectar ações adicionar/remover membros e labels; editar grupo/setor conforme permissões e invalidar consultas.')
add('FE12','Medium',['PROD-25'],'Paciente ainda usa tutorId singular; N:N não representado pela UI','Formulário e payload com tutorId único','apps/desk-web/src/pages/Patients.tsx:68; apps/desk-web/src/pages/Patients.tsx:144; apps/desk-web/src/pages/Patients.tsx:322','Resolver D03 e adaptar API/UI/migração compatível a múltiplos tutores; não declarar N:N entregue.')
add('FE13','High',['PROD-26'],'Admin não possui editor de permissões por papel/vínculo usuário-papel nem gestão completa de membros de times/filas','admin-correct-fixture-1440.png; admin-roles-1440.png','apps/desk-web/src/pages/Admin.tsx:739; apps/desk-web/src/pages/Admin.tsx:745','Manter editor de setores existente, adicionar editor por capacidade efetiva, associação papel e membros com audit/revogação.')
add('FE14','High',['PROD-27'],'Kanban move por select/drag, mas card não abre conversa e só há filtro de setor','kanban-1440.png; card sem anchor/onClick de navegação','apps/desk-web/src/pages/Kanban.tsx:92; apps/desk-web/src/pages/Kanban.tsx:265','Conectar deep-link de conversa e filtros agente/label/prioridade/período/grupo; manter alternativa teclado e feedback de falha.','BROWSER+STATIC')
add('FE15','High',['PROD-30'],'Tasks/Alerts/Contacts/Kanban/Dashboard não assinam realtime nem executam polling bounded','Busca por setInterval/realtime/addEventListener nessas páginas sem ocorrência; fetch inicial/mutação/manual','apps/desk-web/src/pages/Tasks.tsx:84; apps/desk-web/src/pages/Alerts.tsx:76; apps/desk-web/src/pages/Kanban.tsx:108','Invalidação ou polling limitado e estado stale/offline; preservar formulário sujo e reconciliar reconexão.')
add('FE16','Medium',['PROD-28'],'Monólitos de página e duplicação de estados continuam; features/inbox ausente','Inbox1254 linhas, Admin1342, Contacts682; loadFailureFrom repetido','apps/desk-web/src/pages/Inbox.tsx:1; apps/desk-web/src/pages/Admin.tsx:1; apps/desk-web/src/pages/Contacts.tsx:1','Extrações por ownership real de consultas/mutações e adoção de primitivos; preservar comportamento em capturas equivalentes.')
add('FE17','Medium',['PROD-38'],'Percurso E2E produção completo não está implementado na pasta de suites','e2e/production contém somente 01-harness-identity.spec.ts; config permite reuseExistingServer local','playwright.production.config.ts:41; e2e/production/01-harness-identity.spec.ts:1','Criar cenário de atendimento com serviços isolados identificados e impedir reutilização sem prova de identidade; esta auditoria não executou o stack.')
cards=[('PROD-17','PARTIAL_VERIFIED','Boot aguardou /auth/me, sem consultas operacionais antes; deep-link sem capacidade negado; erro de rede recuperável; mobile Escape retorna foco e sidebar inert. 401/403 reais, rotação/WS/cache e principal alterado integrados NOT_RUN.'),('PROD-19','FAIL','AC1–3 incompletos FE02/03; AC4 parcial (polling Inbox presente), integração concorrente NOT_RUN.'),('PROD-20','FAIL','AC1/2 falham FE04/05; AC3 parcial FE06; WSS remoto/upload/cancelamento integrados NOT_RUN.'),('PROD-21','FAIL','AC1/2 incompletos FE07; AC3 não tem invalidação FE15; AC4 HTTP+PG NOT_RUN.'),('PROD-22','FAIL','AC1/3 falham FE08/09; autoria server-side não retestada; AC4 parcial, formulário renderizado.'),('PROD-23','PARTIAL','Ack/resolve renderizados; links e atualização faltam FE10/15. Geração/dedup/scheduler backend fora do scout.'),('PROD-24','FAIL','AC1 incompleto FE11; edição/revogação/membership HTTP+browser NOT_RUN.'),('PROD-25','FAIL','AC2 incompleto FE09; AC5 N:N ausente FE12; D03 consta OPEN, não ratificação presumida.'),('PROD-26','FAIL','AC1/2/5 incompletos FE13; editor setor existente. D05 OPEN, ausência de aprovação IA fictícia é correta. Audit/revogação integradas NOT_RUN.'),('PROD-27','FAIL','AC1 navegação e AC2 filtros incompletos FE14; alternativa select presente; sincronização FE15; D04 OPEN.'),('PROD-28','PARTIAL','Primitivos e tokens existem; extração/ownership e ledger não fechados FE16; antes/depois não aplicável ao scout.'),('PROD-29','FAIL','AC1 reproduzido FE01. AC2 matriz parcial (não todas 16 rotas×5); leitor de tela/contraste/zoom/motion AC3 NOT_RUN. Capturas nativas e JSON existentes, não crítica final.'),('PROD-30','FAIL','AC1 atualização ausente FE15; KPI backend/PG AC2/3 não avaliado nesta lane.'),('PROD-38','NOT_RUN','Apenas browser sintético com mocks; nenhum percurso serviços reais, nenhum aceite integrado concedido FE17.')]
manifest=[]
for p in D.glob('*.png'):
 manifest.append(dict(file=p.name,sha256=hashlib.sha256(p.read_bytes()).hexdigest(),captured_at=datetime.datetime.fromtimestamp(p.stat().st_mtime,datetime.timezone.utc).isoformat(),fixture='synthetic-mocked-api'))
report=dict(role='read-only frontend scout, not final independent critic',timestamp=datetime.datetime.now(datetime.timezone.utc).isoformat(),findings=f,cards=[dict(card=a,status=b,assessment=c) for a,b,c in cards],renders=manifest,limitations=['Mocks prove frontend behavior only; no backend authz/persistence/provider/scanner/realtime guarantee','Partial responsive matrix; screen reader, contrast, zoom/reflow, vitals NOT_RUN','Initial admin-1440.png is INVALID_FIXTURE: mock returned entries rather than expected data/stats; corrected in admin-correct-fixture-1440.png; not counted as product failure','Initial Vite dev WS attempted localhost:8080 and was refused; second harness intercepts all WebSockets. No existing server used. No real data.','Canonical message fixture provided ascending input where API may use descending; no message-order defect claimed from captures.'])
(D/'findings.json').write_text(json.dumps(report,ensure_ascii=False,indent=2))
lines=['# Scout frontend — CVG Connect Desk','', 'Avaliação somente leitura usando design-director (quality-rubric/visual-qa), CRITERIOS.md e cards PROD17/19–30/38. Público: operador de atendimento veterinário. Meio: aplicação React/Vite real com API sintética interceptada. Sem alteração de produto/docs. Este parecer não é a crítica independente final.','', '## Evidência atual','', 'Playwright 1.59.1, Chromium headless, Vite7.3.6 próprio em 127.0.0.1:32893; config com envDir vazio (nenhum .env carregado), cache em /tmp, token fictício. Scripts render.cjs/render-auth.cjs e JSON browser-observations.json/browser-auth-admin.json preservam fixtures, consultas, console, geometria e texto. '+str(len(manifest))+' capturas PNG com hashes no findings.json. Capturas selecionadas foram abertas e inspecionadas visualmente; não foram apenas geradas.','', 'Inbox: 375×812,1024×768,1440×900, lista/seleção e contexto tablet. Adicionais: tasks/notes/alerts/admin/kanban/contacts desktop; criação tarefas/notas; boot aguardando/confirmado, erro de rede, deep-link negado e shell mobile aberto/Escape. Não constitui matriz completa do PROD29.','', '## Avanços confirmados','', '- PROD17: com /auth/me atrasado, única consulta observada antes da resposta foi /auth/me; nenhuma conversa/contato/setor foi solicitado. Após confirmação, Inbox liberado.','- Principal com apenas chat:read não vê Administração e deep-link /admin mostra Acesso negado; tentativa de rede falha mostra retry mantendo fronteira fechada.','- Shell mobile: drawer aberto funciona; Escape devolveu foco a Abrir navegação e sidebar recebeu inert. Estados de conexão mostram instabilidade real do harness, não online fictício.','- Layout desktop possui hierarquia e navegação consistente; nomes/estado são legíveis. Composer apresenta erro/estado de envio e chave por intenção no código; Kanban oferece select alternativo ao drag; páginas usam componentes de loading/erro/vazio.','', '## Situação por card','', '| Card | Estado do scout | Fundamentação |','|---|---|---|']
for a,b,c in cards:lines.append(f'| {a} | {b} | {c} |')
lines+=['','## Achados e backlog recomendado','']
for x in f:lines += [f"### {x['id']} — {x['severity']} — {x['title']}",f"Cards: {', '.join(x['cards'])}. Evidência: {x['evidence']}. Fonte: `{x['source']}`. Estado: {x['evidence_kind']}, confiança {x['confidence']}.",'',x['recommendation'],'']
lines+=['## Prioridade sugerida','', '1. FE01 + FE02/03 + FE04/05: corrigir geometria e completar caminho principal de atendimento, timeline e leitura segura.','2. FE07–FE15: fechar contexto de tarefas/notas/alertas, CRUD de memberships/admin e sincronização entre operadores.','3. FE16: extrair componentes/consultas durante as entregas, sem reescrita geral; depois fechar matriz visual e FE17 com serviços reais.','', '## Limites e honestidade de evidência','']+['- '+l for l in report['limitations']]+['- Root executa unit/typecheck/lint; não duplicados por este scout. Não foi conferida cobertura/CI nesta lane.','- D03/D04/D05 continuam OPEN nos documentos lidos. Isso impede afirmar escopo ratificado, sem impedir correções independentes.','- Não emitida nota AAA global: há falhas High observadas e vários requisitos obrigatórios NOT_RUN.','', 'Veredito: frontend substancial e PROD17 avançado; PROD19–30 não estão completos para os critérios declarados. Interrompida investigação após evidência suficiente para backlog reproduzível, sem correções por tratar-se de scout.']
(D/'RELATORIO.md').write_text('\n'.join(lines))
