from pathlib import Path
import json,hashlib,datetime
out=Path('/tmp/cvg-audit-r3-dvlqz0my/frontend')
base=json.load(open('docs/auditorias/2026-09-13-entregas/evidencias/frontend/findings.json'))
assess=[
('BROWSER+STATIC','Fechado a 1024: scrollWidth=1318, rect x1038/right1318, inert=false e aria-hidden ausente; Tab chega ao botão Abrir cadastro do contato. Aberto estabiliza em1024 e Escape restaura foco, mas não corrige estado fechado.','inbox-1024-selected.png; focused-observations.json:closed-drawer-dom/closed-drawer-tab/context-escape-stable','apps/desk-web/src/pages/Inbox.css:17; apps/desk-web/src/pages/Inbox.tsx:1240'),
('BROWSER+STATIC','Transferência permanece disabled; contexto mostra status/setor/início/canal e leva a /contacts genérico, sem atribuição/tags/handoff/tarefa/nota contextuais. Não basta backend operacional existir.','inbox-1440-selected.png; inbox-1024-context-stable.png','apps/desk-web/src/pages/Inbox.tsx:1127; apps/desk-web/src/pages/Inbox.tsx:1249'),
('BROWSER+STATIC','Busca sintética fora da primeira página gera zero request e mostra Nenhuma conversa; total2 continua derivado do lote. fetchConversations passa setor/limit/cursor; wrapper possui status mas tela não o envia.','focused-observations.json:server-search; browser-observations.json:requests','apps/desk-web/src/pages/Inbox.tsx:335; apps/desk-web/src/pages/Inbox.tsx:880; apps/desk-web/src/pages/Inbox.tsx:894; apps/desk-web/src/lib/api.ts:524'),
('BROWSER+STATIC','Histórico sintético de10/11 setembro continua sob separador literal Hoje em13 setembro. Não foi auditada ordem da timeline a partir desta fixture.','inbox-375-selected.png; inbox-1440-selected.png','apps/desk-web/src/pages/Inbox.tsx:1161'),
('BROWSER+STATIC','asset://fixture-doc renderiza exame-luna-fixture.pdf como chip sem link/botão de leitura/download. Componentes/estados de mídia completa e autorização real não demonstrados.','inbox-1440-selected.png','apps/desk-web/src/pages/Inbox.tsx:1163; apps/desk-web/src/pages/Inbox.tsx:1164'),
('BROWSER+STATIC','RASCUNHO SINTETICO R3 desaparece após navegação SPA por links Inbox→Tarefas→Inbox (input vazio). useState/ref local continuam sendo donos de drafts e intenções. Não foi testado401/relogin integrado.','focused-observations.json:draft-after-navigation; render-focused.cjs','apps/desk-web/src/pages/Inbox.tsx:246; apps/desk-web/src/pages/Inbox.tsx:274'),
('BROWSER+STATIC','Formulário só oferece título, descrição, prioridade e prazo; payload omite assignee/vínculos. Card mostra10000000 e não abre conversa vinculada.','tasks-create-1440.png; tasks-1440.png','apps/desk-web/src/pages/Tasks.tsx:129; apps/desk-web/src/pages/Tasks.tsx:357'),
('BROWSER+STATIC','Formulário exige ID da referência; card mostra #20000000 sem navegação. Seletores humanos/contextuais não implementados.','notes-create-1440.png','apps/desk-web/src/pages/Notes.tsx:95; apps/desk-web/src/pages/Notes.tsx:169; apps/desk-web/src/pages/Notes.tsx:243'),
('STATIC','fetchContactDetail carrega notas apenas para data.conversations[0]?.id; criação também escolhe primeira conversa. Agregação/paginação de todas as conversas não existe nesse caminho.','static-evidence.txt','apps/desk-web/src/pages/Contacts.tsx:188; apps/desk-web/src/pages/Contacts.tsx:305; apps/desk-web/src/pages/Contacts.tsx:340'),
('BROWSER+STATIC','Alerta sintético tem conversationId/taskId, mas só expõe Reconhecer/Resolver. Não há navegação ao recurso exato.','alerts-1440.png','apps/desk-web/src/pages/Alerts.tsx:245; apps/desk-web/src/pages/Alerts.tsx:260'),
('STATIC','ContactGroups lista membros sem mutação e orienta adicionar pela ficha; Contacts mostra badges sem controle correspondente de membership. Não há novo caminho frontend.','static-evidence.txt','apps/desk-web/src/pages/ContactGroups.tsx:354; apps/desk-web/src/pages/ContactGroups.tsx:363; apps/desk-web/src/pages/Contacts.tsx:452'),
('STATIC','Estado/formulário/payload de Patients mantêm tutorId singular. N:N e ratificação D03 não podem ser considerados entregues pela UI.','static-evidence.txt','apps/desk-web/src/pages/Patients.tsx:68; apps/desk-web/src/pages/Patients.tsx:144; apps/desk-web/src/pages/Patients.tsx:322'),
('BROWSER+STATIC','Usuários mantêm editor Setores e delete; papéis exibem nome/descrição/delete, sem editor de capacidades ou vínculo usuário↔papel. Filas/times continuam tabelas simples sem gestão completa de membros.','admin-correct-fixture-1440.png; admin-roles-1440.png','apps/desk-web/src/pages/Admin.tsx:739; apps/desk-web/src/pages/Admin.tsx:745; apps/desk-web/src/pages/Admin.tsx:756'),
('BROWSER+STATIC','Kanban possui drag/select de mudança de status e filtro setor; card não abre conversa e faltam filtros agente/label/prioridade/período/grupo.','kanban-1440.png','apps/desk-web/src/pages/Kanban.tsx:92; apps/desk-web/src/pages/Kanban.tsx:265'),
('STATIC','Tasks/Alerts/Contacts/Kanban/Dashboard continuam fetch inicial, mutação ou refresh manual. Não há assinatura realtime/polling bounded nessas páginas; timers de feedback/debounce não atualizam dados de outro operador.','static-evidence.txt','apps/desk-web/src/pages/Tasks.tsx:84; apps/desk-web/src/pages/Alerts.tsx:76; apps/desk-web/src/pages/Contacts.tsx:198; apps/desk-web/src/pages/Kanban.tsx:108; apps/desk-web/src/pages/Dashboard.tsx:37'),
('STATIC','Inbox1254 linhas/Admin1342/Contacts682; apps/desk-web/src/features não existe e loadFailureFrom continua repetido. Primitivos/tokens existentes não fecham extração por ownership.','source-hashes-before.json; static-evidence.txt','apps/desk-web/src/pages/Inbox.tsx:1; apps/desk-web/src/pages/Admin.tsx:1; apps/desk-web/src/pages/Contacts.tsx:1'),
('STATIC','e2e/production contém apenas01-harness-identity.spec.ts; config production inclui suites AAA existentes, mas não os novos percursos completos. reuseExistingServer:!CI permanece. Stack real não executado por esta lane.','static-evidence.txt','playwright.production.config.ts:41; e2e/production/01-harness-identity.spec.ts:1')]
findings=[]
for old,(kind,assessment,evidence,source) in zip(base['findings'],assess):
 findings.append({'id':old['id'],'status':'OPEN','severity':old['severity'],'cards':old['cards'],'title':old['title'],'assessment_r3':assessment,'evidence_kind':kind,'evidence':evidence.split('; '),'source':source.split('; '),'remaining':old['recommendation'],'new_progress':'Nenhum delta identificado nas fontes frontend comparáveis à R2.','confidence':'HIGH' if kind=='BROWSER+STATIC' else 'HIGH_STATIC_ONLY'})
hashes=json.loads((out/'source-hashes-before.json').read_text())
# Exclude generated dist from source denominator.
hashes=[x for x in hashes if '/dist/' not in x['path']]
(out/'source-hashes-before.json').write_text(json.dumps(hashes,indent=2))
after=[]
for r in hashes:
 h=hashlib.sha256(Path(r['path']).read_bytes()).hexdigest();after.append({'path':r['path'],'sha256':h,'unchanged_during_r3':h==r['sha256']})
(out/'source-hashes-after.json').write_text(json.dumps(after,indent=2))
inspected=['inbox-375-selected.png','inbox-1024-selected.png','inbox-1440-selected.png','inbox-1024-context.png','inbox-1024-context-stable.png','tasks-create-1440.png','notes-create-1440.png','admin-correct-fixture-1440.png','admin-roles-1440.png','alerts-1440.png','kanban-1440.png','auth-boot-pending-1440.png','auth-deeplink-denied-1440.png','auth-offline-retry-1440.png','shell-mobile-nav-open.png']
limitations=['API inteiramente sintética via route; screenshots provam somente UI atual. Nenhum E2E/backend/DB/autorização real/provider/scanner/persistência/realtime remoto validado.','WebSockets fechados propositalmente para não acessar servidor externo/preexistente. Mensagens de erro HMR Vite e banner de reconexão são efeitos do harness, não defeitos novos de produto.','Nenhum pageerror observado; auth offline gera ERR_FAILED intencional.','Captura inbox-1024-context.png foi colhida durante transição e não é usada para geometria aberta final: substituída por inbox-1024-context-stable.png com450ms de estabilização.','Matriz parcial: Inbox375/1024/1440 e páginas adjacentes desktop; não16 rotas×5 viewports, fronteiras, zoom/reflow, contraste ou leitor de tela real. Não concede G07/G12/AAA.','Fixture histórica de mensagens não constitui prova de ordenação/empates/timezone completo. FE04 limita-se a Hoje literal sobre dias anteriores.','Baseline R2 é sources-before.json arquivado em /tmp/cvg-audit-deliveries-ufq9_ejh, não apenas gitHEAD; árvore preexistente contém modificações.77 arquivos src e5 configurações/lock comparáveis idênticos; suite identity tem hash atual, sem baseline naquele mapa.','Tentativas de startup iniciais falharam por path vite raiz e bundling CJS; comando bem-sucedido usa apps/desk-web/node_modules/vite/bin/vite.js e --configLoader native. Sem mudança produtiva.']
report={'role':'read-only frontend scout R3, not final independent critic','timestamp':datetime.datetime.now(datetime.timezone.utc).isoformat(),'run_id':'cvg-audit-r3-dvlqz0my','status_counts':{'RESOLVED':0,'PARTIAL':0,'OPEN':17,'NOT_REVALIDATED':0},'findings':findings,'new_progress':[],'preserved_progress':['Boot espera /auth/me antes da consulta operacional na fixture; deep-link admin sem capacidade exibe Acesso negado; erro de rede oferece retry.','Shell mobile: Escape restaura foco Abrir navegação e sidebar fechada inert.','Contexto aberto: Escape restaura foco Abrir informações da conversa; esta melhoria já existente não resolve FE01 fechado.','Primitivos/tokens, estados de erro/retry, select acessível Kanban e editor de setores Admin existentes foram preservados.'], 'source_comparison':{'compared_to':'/tmp/cvg-audit-deliveries-ufq9_ejh/sources-before.json','total_current_source_files':len(hashes),'comparable':sum(x['equal_r2'] is not None for x in hashes),'identical':sum(x['equal_r2'] is True for x in hashes),'changed':sum(x['equal_r2'] is False for x in hashes),'unmatched':[x['path'] for x in hashes if x['equal_r2'] is None],'changed_during_r3':[x['path'] for x in after if not x['unchanged_during_r3']]},'renders':[{'file':p.name,'sha256':hashlib.sha256(p.read_bytes()).hexdigest(),'fixture':'SYNTHETIC API MOCKS','inspected':p.name in inspected} for p in sorted(out.glob('*.png'))],'inspected_renders':inspected,'limitations':limitations,'visual_verdict':'FAIL for scoped acceptance; no overall design score/AAA assigned from partial matrix','commands':['node apps/desk-web/node_modules/vite/bin/vite.js --config /tmp/cvg-audit-r3-dvlqz0my/frontend/vite.config.mjs --configLoader native','node /tmp/cvg-audit-r3-dvlqz0my/frontend/render.cjs','node /tmp/cvg-audit-r3-dvlqz0my/frontend/render-auth.cjs','node /tmp/cvg-audit-r3-dvlqz0my/frontend/render-focused.cjs']}
(out/'findings-r3.json').write_text(json.dumps(report,indent=2,ensure_ascii=False))
md=['# Revalidação frontend R3 — scout somente leitura','',f"17/17 achados FE continuam OPEN. Nenhum avanço novo foi identificado nas fontes frontend: {report['source_comparison']['identical']}/{report['source_comparison']['comparable']} arquivos comparáveis idênticos à baseline R2, incluindo77 arquivos de src. A suite identity possui hash atual, sem baseline naquele mapa. Todos83 arquivos permaneceram iguais durante esta lane.",'','Renderer Vite próprio em127.0.0.1:43543, Playwright Chromium por ausência de browser tool. API/mock e usuário sintéticos explicitamente rotulados; nenhuma alegação de E2E. Aplicado design-director em modo design audit, aceites docs/melhorias-2026-09-13 e escopo FE01–17. Fonte/capturas/requests/foco/console registrados.','', '## Evidência decisiva','', '- FE01: fechado a1024 amplia documento para1318, inert=false e Tab alcança controle invisível. Aberto estabiliza1024 e Escape devolve foco; o estado fechado ainda falha.', '- FE06: navegação SPA via links Inbox→Tarefas→Inbox apaga rascunho sintético.','- FE03: digitar busca fora do lote não gera request e exibe vazio, com contagens locais.','- Capturas atuais inspecionadas confirmam Hoje fixo, anexo como chip, transferência disabled, formulário de tarefa incompleto, ID técnico em notas e tabelas Admin sem editor de papel/membership.','', '## Status por achado','']
for f in findings:
 md += [f"### {f['id']} — {f['status']} · {f['severity']}",'',f['assessment_r3'],'', 'Fonte: '+ '; '.join(f['source'])+'.','Evidência: '+ '; '.join(f['evidence'])+'.','Restante: '+f['remaining'],'']
md += ['## Progresso existente preservado','']+['- '+x for x in report['preserved_progress']]+['','## Limites','']+['- '+x for x in limitations]+['','## Handoff','', 'Artefatos: findings-r3.json, source-hashes-before.json, source-hashes-after.json, runtime.json, browser-observations.json, browser-auth-admin.json, focused-observations.json, static-evidence.txt e capturas PNG. Novos testes unitários/build são responsabilidade da lane lead; nenhum resultado unitário inferido aqui.','', 'Prioridade restante: corrigir drawer/foco e completar operação/contexto usando contratos backend já entregues; depois timeline/mídia/recuperação, formulários humanos/vínculos, memberships/admin, sincronização e E2E real. Não reimplementar capacidades backend com base na ausência de UI.']
(out/'RELATORIO-R3.md').write_text('\n'.join(md)+'\n')
# Bind narrow source excerpts as independent evidence.
excerpts={'apps/desk-web/src/pages/Inbox.tsx':[(242,279),(335,351),(880,895),(1120,1132),(1157,1190),(1238,1253)],'apps/desk-web/src/pages/Inbox.css':[(17,19)],'apps/desk-web/src/pages/Tasks.tsx':[(81,96),(127,138),(350,365)],'apps/desk-web/src/pages/Notes.tsx':[(92,99),(155,177),(239,246)],'apps/desk-web/src/pages/Contacts.tsx':[(185,190),(301,314),(449,459)],'apps/desk-web/src/pages/Patients.tsx':[(65,69),(142,146),(319,331)],'apps/desk-web/src/pages/ContactGroups.tsx':[(350,367)],'apps/desk-web/src/pages/Admin.tsx':[(739,767)],'apps/desk-web/src/pages/Alerts.tsx':[(73,88),(243,270)],'apps/desk-web/src/pages/Kanban.tsx':[(88,110),(261,277)],'apps/desk-web/src/pages/Dashboard.tsx':[(35,49),(78,87)],'playwright.production.config.ts':[(37,44)]}
text=[]
for file,ranges in excerpts.items():
 lines=Path(file).read_text().splitlines()
 for start,end in ranges:
  text.append('\n'+file)
  text.extend(f'{i}: {lines[i-1]}' for i in range(start,end+1))
text+=['\nInventory e2e/production:']+[str(p) for p in Path('e2e/production').rglob('*') if p.is_file()]
(out/'static-evidence.txt').write_text('\n'.join(text)+'\n')
print(json.dumps(report['source_comparison'],indent=2));print('written',out/'RELATORIO-R3.md')
