import json
from pathlib import Path
out=Path('/tmp/cvg-audit-r3-dvlqz0my/ops')
rows=[
{'id':'OPS01','status':'RESOLVED','evidence':['scripts/triple-aaa-verify.mjs:159','scripts/production/prod-02.test.mjs:445','node-tests.log: OPS01 — reavaliação com imageDigest diferente reprova o candidato PASS'],'assessment':'Drift compara agora imageDigest live e selado; regressão CLI executada rejeita troca exclusiva do digest.','tasks':['PROD-02','PROD-35'],'limits':'Resolução do bypass do CLI; não prova identidade da imagem efetivamente entregue (OPS06).'},
{'id':'OPS02','status':'RESOLVED','evidence':['scripts/production/evidence-gate.mjs:330','scripts/production/evidence-gate.mjs:741','scripts/production/prod-02.test.mjs:410','scripts/production/prod-02.test.mjs:455','node-tests.log'],'assessment':'Reprodução original de manifesto de comando contraditório é rejeitada: comando/escopo, exit, conteúdo de log, futuro e metadados validados; coverage exige denominadores e tabela.','tasks':['PROD-02','PROD-34'],'limits':'Resolução limitada ao manifesto de comando original. Via derivada de artefatos tem lacuna nova R3-OP02; não comprova coverage global real.'},
{'id':'OPS03','status':'PARTIAL','evidence':['scripts/production/evidence-gate.mjs:496','scripts/production/evidence-gate.mjs:528','scripts/production/evidence-gate.mjs:970','query-probe.log'],'assessment':'[{}] agora INVALID e 11 identidades são exigidas. Porém medições null, acima do orçamento e em 2099 ainda PASS no default evaluateCheck; detalhado R3-OP01.','tasks':['PROD-02','PROD-33'],'limits':'Probe usa payload sintético e função real; nenhuma medição SQL/DB executada.'},
{'id':'OPS04','status':'RESOLVED','evidence':['.github/scripts/certification-aggregator.mjs:217','.github/scripts/certification-aggregator.mjs:484','scripts/production/prod-03.test.mjs:379','node-tests.log'],'assessment':'main preserva evento solicitado; política desconhecida produz FAILED. Regressores de typo e main foram executados.','tasks':['PROD-03'],'limits':'Política local comprovada; rulesets/checks required remotos não consultados.'},
{'id':'OPS05','status':'OPEN','evidence':['scripts/staging-smoke.mjs:11','scripts/staging-smoke.mjs:42','scripts/staging-smoke.mjs:43'],'assessment':'DeleteObjectCommand continua sem import; referência falha após put/get. HEAD de objeto apagado não trata 404 e condição mantém || true.','tasks':['PROD-32'],'limits':'CURRENT_STATIC, não se contatou S3/ClamAV/collector. Não duplicar como novo achado.'},
{'id':'OPS06','status':'PARTIAL','evidence':['.github/workflows/triple-aaa-gate.yml:214','.github/workflows/triple-aaa-gate.yml:233','.github/scripts/certification-aggregator.mjs:164','.github/scripts/certification-aggregator.mjs:186'],'assessment':'Manifesto ganhou source/lock/run/attempt/tempo e validação correspondente; permanece digest docker inspect .Id de build efêmero separado, sem prova de registry manifest ou igualdade boot/scan/E2E/entrega.','tasks':['PROD-03','PROD-35','PROD-38'],'limits':'CURRENT_STATIC. Nenhum Docker build/push/boot ou CI remoto executado.'},
{'id':'OPS07','status':'PARTIAL','evidence':['docs/producao-2026-09-13/evidencias/prod-00/baseline/candidate-manifest.json:1','baseline-drift.json','docs/producao-2026-09-13/evidencias/prod-36/prod-36-evidence.json:1'],'assessment':'Baseline atual PROD00: 42/42 fileHashes correspondem aos arquivos presentes, zero drift (não repetir seis divergências antigas). PROD36 ainda commit string/resultado narrativo sem source/lock/digests/hashes de artefato e horários completos por run.','tasks':['PROD-00','PROD-36','PROD-40'],'limits':'Não rodado PROD00 por escrita no repo; verificação estática de hashes não equivale a novo selo integrado nem qualifica todos os 481 paths de status Git.'},
{'id':'OPS08','status':'OPEN','evidence':['infra/scripts/dr-e2e.sh:12','infra/scripts/dr-e2e.sh:30','infra/scripts/dr-e2e.sh:117','infra/scripts/dr-e2e.sh:135','infra/scripts/pg-restore.sh:16'],'assessment':'Bancos src/dst fixos são apagados sem ownership; backup /tmp, integridade de fixture só grep tag, sem igualdade outbox/DLQ; pg-restore permite ausência de checksum.','tasks':['PROD-37'],'limits':'CURRENT_STATIC, script destrutivo deliberadamente não executado. RPO/RTO e restore mídia/erasures não observados.'}
]
new=[
{'id':'R3-OP01','severity':'High','confidence':'high','status':'OPEN','related_previous':'OPS03','title':'Query gate aceita medições nulas ou acima do orçamento e datas futuras','criterion':'G01/G11; PROD-02 adversariais e PROD-33 medição real','evidence_kind':'CURRENT_REPRO','references':['scripts/production/evidence-gate.mjs:528','scripts/production/evidence-gate.mjs:530','scripts/production/evidence-gate.mjs:532','/tmp/cvg-audit-r3-dvlqz0my/ops/query-probe.log'],'reproduction':'node /tmp/cvg-audit-r3-dvlqz0my/ops/query-probe.mjs. Usa DEFAULT_CHECKS query-performance, 11 nomes obrigatórios e identidade coincidente. Cenários null-measurements, over-budget, future-measurements retornam PASS/reasons=[]. Controle [{}] retorna INVALID.','impact':'Gate pode aprovar alegação de performance sem números reais ou com números explicitamente fora do limite.','cause':'Number(null) vira 0; não compara totalCost/planRows ao budget; aceita withinBudget/acceptable declarativos; measuredAt só parseável. Não exige SQL/plano.','proposed':'Exigir tipos number finitos, linhas inteiras, identidade/SQL/plano, janela temporal, orçamento congelado e calcular aderência do número ao orçamento; negativos isolados para null, string vazia, excedente e futuro.','tasks':['PROD-02','PROD-33'],'owner':'responsáveis PROD-02 e PROD-33','limits':'Fixture sintética exercita validador real; não significa produtor atual gera nulos ou que banco real excede orçamento.'},
{'id':'R3-OP02','severity':'High','confidence':'high','status':'OPEN','related_previous':'OPS02 (via distinta da reprodução original corrigida)','title':'Artefato derivado dispensa runId/attempt exigidos pelo contrato de evidência','criterion':'G01/G12; CRITERIOS Estados e validade','evidence_kind':'CURRENT_REPRO','references':['scripts/production/evidence-gate.mjs:441','scripts/production/evidence-gate.mjs:551','scripts/production/evidence-gate.mjs:570','scripts/production/evidence-gate.mjs:690','/tmp/cvg-audit-r3-dvlqz0my/ops/query-probe.log'],'reproduction':'Cenário missing-run-metadata remove runId/attempt do payload, preservando 11 queries numéricas válidas, identidade e data atual; evaluateCheck retorna PASS sem manifesto separado.','impact':'Manifesto de comando reprova ambiente sem run/attempt, mas mesma obrigação C10 é contornada para artefato derivado, impedindo atribuição confiável ao run/attempt.','cause':'Retorno precoce de deriveArtifactManifest não passa validateManifestShape; validateArtifactPayload ignora runId/attempt e derivado só contém kind/producer no environment.','proposed':'Validar run/attempt e vínculo esperado tanto no payload quanto no manifesto derivado; preservar metadados e exigir mesma semântica de identidade/tempo em todas vias.','tasks':['PROD-02','PROD-03','PROD-40'],'owner':'responsável PROD-02, integração PROD-03, revisão PROD-40','limits':'Não é repetição de command=true/exit99/log vazio, que está corrigido. Probe local, sem falsificar prova externa.'}
]
data={'audit':'R3 OPS read-only','revision':'754f9badac46278e77d21de91c58eedb15e80581','skills':['engineering-framework','backend-patterns'],'previous_findings':rows,'new_findings':new,'verification':{'node_tests':{'status':'PASS','count':47,'breakdown':{'PROD-02':25,'PROD-03':17,'PROD-36':5},'log':str(out/'node-tests.log')},'realtime_public_http':{'status':'PASS','count':3,'evidence':['apps/realtime-service/src/index.ts:247','apps/realtime-service/src/__tests__/realtime-health.test.ts:122',str(out/'realtime-health.log')],'observed':'HTTP produção:503 sem token;401 anônimo e token errado;200 com Bearer correto inclusive query string; Prometheus content-type/body','limits':'Servidor real local com porta de autorização fixture; não runtime Docker ou scrape Prometheus real.'},'metrics_wiring':{'status':'PASS_STATIC','evidence':['docker-compose.yml:241','docker-compose.yml:280','docker-compose.yml:287','docker-compose.staging.yml:85','docker-compose.staging.yml:245','infra/prometheus/prometheus.yml:12'],'observed':'Produção exige METRICS_TOKEN por interpolation em API/worker/realtime/Prometheus; staging usa mesmo token de fixture; Prometheus grava tmpfs umask077 e três targets usam authorization Bearer credentials_file.','limits':'docker compose config e scrape não reexecutados neste lane; não transforma wiring estático em prova de infra.'}},'limitations':['Sem execução DB, Docker, deploy, rede externa, smoke integrações, DR ou PROD00.','Somente escrita em diretório /tmp da auditoria, nenhum produto/docs editado.','Sem qualificação de release: critérios G01/G09/G10/G11/G12 continuam com lacunas dentro deste escopo.','Leitura de baseline foi recalculada: 42/42 hashes, sem reaproveitar drift anterior.']}
(out/'findings.json').write_text(json.dumps(data,ensure_ascii=False,indent=2)+'\n')
lines=['# R3 — OPS, métricas e evidências','', 'Revisão read-only do candidato `754f9badac46278e77d21de91c58eedb15e80581`, worktree com alterações. Critérios congelados: `docs/melhorias-2026-09-13/CRITERIOS.md`. Artefatos desta lane em `/tmp/cvg-audit-r3-dvlqz0my/ops`.','', '**Resultado: houve correções reais, mas o escopo ainda não qualifica produção.** PROD02 25/25 + PROD03 17/17 + PROD36 5/5 = 47/47; realtime-health 3/3 passou pelo servidor HTTP real em loopback. O `/metrics` bloqueia sem token em produção, rejeita anônimo/token incorreto e aceita Bearer configurado. Compose/Prometheus estão conectados estaticamente; scrape real não foi observado.','', '| Anterior | R3 | Evidência e limite |','|---|---|---|']
for r in rows:lines.append(f"| {r['id']} | {r['status']} | {r['assessment']} Referências: {', '.join(r['evidence'])}. Limite: {r['limits']} |")
lines+=['','## Novos achados']
for f in new:lines+=['',f"### {f['id']} — {f['title']} ({f['severity']})",'',f['reproduction'],'',f['impact'],'',f"Prova: {', '.join(f['references'])}.",'',f"Tarefas: {', '.join(f['tasks'])}. Correção para revalidação: {f['proposed']}",'',f"Limite: {f['limits']}"]
lines+=['','## Limites e próximo passo','', 'Não executados: PROD00 (escreve evidência no repo), bancos, Docker/compose config/up, CI remoto, S3/ClamAV/collector, scans, carga, DR, restore, deploy. A suite realtime completa/AAA05 não foi repetida; só health, porque o lead cobre regressão mais ampla. Não houve implementação.','', 'Corrigir R3-OP01/02 em PROD02/33 e concluir OPS05/06/07/08 com responsáveis já atribuídos. Revalidar contraprovas locais, depois obter evidência da infraestrutura real e de um único candidato final.','', 'Artefatos: `findings.json`, `node-tests.log`, `realtime-health.log`, `query-probe.mjs`, `query-probe.log`, `baseline-drift.json`, `source-hashes.json`, `source-lines.log`.']
(out/'report.md').write_text('\n'.join(lines)+'\n')
